# Generated by Django 3.1.7 on 2021-02-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20210228_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='primer_apellido',
            field=models.CharField(max_length=50, verbose_name='Primer apellido'),
        ),
    ]
