# Generated by Django 3.1.7 on 2021-02-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_auto_20210228_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='clave_abaco',
            field=models.CharField(blank=True, max_length=50, verbose_name='clave ABaco'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuario_abaco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuario ABaco'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='correo institucional'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nip',
            field=models.CharField(max_length=50, verbose_name='documento'),
        ),
    ]
