# Generated by Django 3.1.7 on 2021-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_usuarios_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nip',
            field=models.CharField(blank=True, max_length=50, verbose_name='documento'),
        ),
    ]
