# Generated by Django 3.1.7 on 2021-03-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0007_auto_20210301_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nip',
            field=models.IntegerField(blank=True, verbose_name='documento'),
        ),
    ]
