# Generated by Django 3.1.7 on 2021-03-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0008_auto_20210301_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nip',
            field=models.IntegerField(blank=True, max_length=50, verbose_name='documento'),
        ),
    ]
