# Generated by Django 3.1.7 on 2021-03-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0009_auto_20210301_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nip',
            field=models.BigIntegerField(blank=True, verbose_name='documento'),
        ),
    ]
